### ISSUE TITLE
TypeScript: Could not find a declaration file for module 'three-conic-polygon-geometry'.

### ISSUE THREAD

**Issue by LrDevEng** [vasturiano/three-conic-polygon-geometry#11]
Hello,

I've noticed the following issue while converting from JS to TS in one of my projects:

![image](https://github.com/user-attachments/assets/509d86df-e21a-4c84-8305-14d4b38f8abc)

> Could not find a declaration file for module 'three-conic-polygon-geometry'.

Version: **1.6.4**
I am using ESM ("type": "module" in package.json).

This does also show some issues:
https://arethetypeswrong.github.io/?p=three-conic-polygon-geometry%401.6.4

Thanks for the great package!

**Comment by vasturiano** [comment]
@LrDevEng thanks for reaching out.

I've just added types exports to the package. Looks good here now:
https://arethetypeswrong.github.io/?p=three-conic-polygon-geometry%401.6.5

**Comment by LrDevEng** [comment]
@vasturiano thank you very much for the super fast update.
After updating to version 1.6.5 in my project the TS import error is fixed.
